interface Data {
    firstName: string;
    lastName: string;
    tableNumber: string;
}

export const data: Data[] = [
    { firstName: "Γιάννης", lastName: "Αλεξίου", tableNumber: "3" },
    { firstName: "Νίκος", lastName: "Ανατασίου", tableNumber: "1" },
    { firstName: "Ελεάννα", lastName: "Ασβεστοπούλου", tableNumber: "7" },
    { firstName: "Γιώργος", lastName: "Ασβεστοπούλου", tableNumber: "7" },
    { firstName: "Ιφιγένεια", lastName: "Βασιλειάδου", tableNumber: "4" },
    { firstName: "Βαρβάρα", lastName: "Γεωργίου", tableNumber: "9" },
    { firstName: "Βασίλης", lastName: "Βογιατζής", tableNumber: "1" },
    { firstName: "Δέσποινα", lastName: "Βουλγαρόγλου", tableNumber: "1" },
    { firstName: "Μιχάλης", lastName: "Γεώργας", tableNumber: "1" },
    { firstName: "Αλεξία", lastName: "Γεωργιάδου", tableNumber: "4" },
    { firstName: "Νίκος", lastName: "Γεωργιάδης", tableNumber: "2" },
    { firstName: "Γιώργος", lastName: "Γεωργιανάκης", tableNumber: "8" },
    { firstName: "Γιώργος", lastName: "Γεωργιανάκης", tableNumber: "8" },
    { firstName: "Θοδωρής", lastName: "Γεωργιανάκης", tableNumber: "9" },
    { firstName: "Μαρία", lastName: "Γκαρούτσου", tableNumber: "1" },
    { firstName: "Αφροδίτη", lastName: "Ζύγου", tableNumber: "5" },
    { firstName: "Μίλτος", lastName: "Ζώγκας", tableNumber: "7" },
    { firstName: "Μαρία", lastName: "Ηλοπούλου", tableNumber: "4" },
    { firstName: "Κωνσταντίνα", lastName: "Θεοδώρου", tableNumber: "5" },
    { firstName: "Κώστας", lastName: "Κακουδάκης", tableNumber: "1" },
    { firstName: "Άννα", lastName: "Καπέτου", tableNumber: "6" },
    { firstName: "Γιώργος", lastName: "Καπέτος", tableNumber: "6" },
    { firstName: "Δήμος", lastName: "Καραφυλλιάς", tableNumber: "1" },
    { firstName: "Κώστας", lastName: "Κατριμουστάκης", tableNumber: "5" },
    { firstName: "Χρήστος", lastName: "Κεχαγιάς", tableNumber: "9" },
    { firstName: "Νίκος", lastName: "Κλιούμης", tableNumber: "2" },
    { firstName: "Αλίκη", lastName: "Κοντογιάννη", tableNumber: "8" },
    { firstName: "Εύη", lastName: "Κοντογιάννη", tableNumber: "8" },
    { firstName: "Χριστίνα", lastName: "Κοντογιάννη", tableNumber: "9" },
    { firstName: "Ρόζα", lastName: "Κωνσταντινίδου", tableNumber: "5" },
    { firstName: "Γεωργιανάκης", lastName: "Θοδωρής", tableNumber: "9" },
    { firstName: "Μαρία", lastName: "Γκαρούτσου", tableNumber: "1" },
    { firstName: "Γεωργία", lastName: "Λιαροπούλου", tableNumber: "5" },
    { firstName: "Αλέξανδρος", lastName: "Λεβεντογιάννης", tableNumber: "3" },
    { firstName: "Κική", lastName: "Μαύρου", tableNumber: "8" },
    { firstName: "Κώστας", lastName: "Μάυρος", tableNumber: "9" },
    { firstName: "Μάγια", lastName: "Μάυρου", tableNumber: "9" },
    { firstName: "Ερμιόνη", lastName: "Μελεκοπούλου", tableNumber: "6" },
    { firstName: "Μαριλένα", lastName: "Μιχαλοπούλου", tableNumber: "2" },
    { firstName: "Στέλλα", lastName: "Μιχαλοπούλου", tableNumber: "2" },
    { firstName: "Έλια", lastName: "Μπίλλα", tableNumber: "2" },
    { firstName: "Άννα", lastName: "Μπόζη", tableNumber: "7" },
    { firstName: "Ζωή", lastName: "Μπόζη", tableNumber: "7" },
    { firstName: "Κώστας", lastName: "Μπόζης", tableNumber: "7" },
    { firstName: "Σοφία", lastName: "Μπόζη", tableNumber: "7" },
    { firstName: "Δημήτρης", lastName: "Νικηφορίδης", tableNumber: "5" },
    { firstName: "Ελευθερία", lastName: "Παναγιώτου", tableNumber: "2" },
    { firstName: "Γιάννα", lastName: "Παναγιωτίδου", tableNumber: "7" },
    { firstName: "Γιούλη", lastName: "Παναγιωτίδου", tableNumber: "4" },
    { firstName: "Τραιανός", lastName: "Παναγιωτίδης", tableNumber: "4" },
    { firstName: "Σπύρος", lastName: "Παναγιωτίδης", tableNumber: "8" },
    { firstName: "Ρεγγίνα", lastName: "Παπαδημητρίου", tableNumber: "9" },
    { firstName: "Ελένη", lastName: "Παπασταματίου", tableNumber: "5" },
    { firstName: "Εβίτα", lastName: "Παπαστόιτση", tableNumber: "9" },
    { firstName: "Κώστας", lastName: "Παπαστόιτσης", tableNumber: "8" },
    { firstName: "Τατιάνα", lastName: "Παπαστόιτση", tableNumber: "4" },
    { firstName: "Φιλιώ", lastName: "Παπαστόιτση", tableNumber: "8" },
    { firstName: "Βασίλης", lastName: "Παρασκευαΐδης", tableNumber: "6" },
    { firstName: "Έλενα", lastName: "Παρασκευαΐδη", tableNumber: "6" },
    { firstName: "Θανάσης", lastName: "Παρασκευαΐδης", tableNumber: "6" },
    { firstName: "Ιωάννης", lastName: "Παρασκευαΐδης", tableNumber: "5" },
    { firstName: "Μάνος", lastName: "Περισυνακης", tableNumber: "4" },
    { firstName: "Μαρία", lastName: "Πριμηκήρη", tableNumber: "3" },
    { firstName: "'Ευα", lastName: "Ρακοβιτη", tableNumber: "2" },
    { firstName: "Γιάννης", lastName: "Σαββίδης", tableNumber: "6" },
    { firstName: "Αννέτα", lastName: "Στάχταρη", tableNumber: "6" },
    { firstName: "Άσπα", lastName: "Συμβουλίδου", tableNumber: "3" },
    { firstName: "Βικέντιος", lastName: "Τσαρτσής", tableNumber: "2" },
    { firstName: "Σπύρος", lastName: "Τσιριγκάκης", tableNumber: "2" },
    { firstName: "Mιχάλης", lastName: "Τσίτας", tableNumber: "5" },
    { firstName: "Μαριλένα", lastName: "Χαραλαμπίδη", tableNumber: "6" },
    { firstName: "Diana-Alexandra", lastName: "Amariei", tableNumber: "3" },
    { firstName: "Jesús García", lastName: "Bascuñán", tableNumber: "3" },
    { firstName: "Peter", lastName: "Gölzhäuser", tableNumber: "3" },
    { firstName: "Mae el", lastName: "Hamoud", tableNumber: "3" },
    { firstName: "Stefan", lastName: "Hank", tableNumber: "3" },
    { firstName: "Katharina", lastName: "Ivic", tableNumber: "3" },
    { firstName: "Adrian", lastName: "Schleyer", tableNumber: "2" }
]